name             'windows_dhcp'
maintainer       'Sous Chefs'
maintainer_email 'help@sous-chefs.org'
license          'MIT'
description      'Installs/Configures windows_dhcp'
version          '0.2.0'
source_url       'https://github.com/sous-chefs/windows_dhcp'
issues_url       'https://github.com/sous-chefs/windows_dhcp/issues'
supports         'windows', '>= 6.2'
chef_version     '> 14'
