name             'windows_dhcp'
maintainer       'Texas A&M'
maintainer_email 'dgroh@arch.tamu.edu'
license          'MIT'
description      'Installs/Configures windows_dhcp'
version          '0.2.0'
supports         'windows', '>= 6.2'
chef_version     '> 14'
issues_url       'https://github.com/TAMUArch/cookbook.windows_dhcp/issues'
source_url       'https://github.com/TAMUArch/cookbook.windows_dhcp'
